---

ignore: |
  **/testdata/

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length:
    max: 120
    level: warning
